
# CONCLUSIONS

The present study presents a comprehensive description of district and distrit governors profiles and explores the linkages between characteristics of districts, district governors, and public perceptions across the country. The study bases its findings on a wealth of data that includes all districts, all district governors and a nationally representative sample of Afghans’ public opinion. Given the extent of the data, a great number of linkages are explored and presented in detail throughout this study.

The findings demonstrate a complex picture of districts, district governors, and public perceptions. A few paradoxical relationships surface that further reveal a complex nature of the possible correlations. For example, opium poppy cultivation is found to have a positive relationship with the level of optimism and even positive views about the role of government in improving living conditions among Afghans.

The study looked at 128 relationship between characteristics of districts, district governors, and public perception indicators. Given the amount of information, readers are required to study the whole report to develop a holistic picture of the subject. Nonetheless, a correlation matrix between indicators of interest is developed to help provide a simple yet complete picture of how districts, district governors and public perceptions interact.

Overall, the main findings of this report can be summarized in the following points:

-	Districts with higher grade, while have better endowments (e.g. security, proximity, highway, mines, and poppy cultivation), their residents hold more negative views, such as lower perception of optimism and perception that government has been unsuccessful in improving living conditions. This counter-intuitive relationship could be explained by differences in expectation among residents of grade 1, grad2 and grade 3 districts. 
-	Access to highway is correlated with positive views about the country’s future and feeling more secure. Access to highway is also correlated with higher level of opium poppy cultivation and experience of corruption while district governors’ office or municipalities.
-	Security is correlated with district grade, but it is not correlated with other district characteristics at macro level. Furthermore, security has positive relationship with competitive type of appointments and a negative relationship with nativity of district governors. Security is correlated with negative perceptions as well.
-	Proximity to provincial centers is correlated with positive public perceptions about optimism and about government improving living conditions, but negative perceptions about feeling safety.
-	Opium poppy cultivation is negatively correlated with presence of natural resources (mines) in a district, but has a positive relation with access to highway. Furthermore, opium poppy cultivation is positively correlated with public optimism, positive perceptions about government in improving living conditions. Furthermore, opium poppy cultivation is associated with lower level of reported experience of corruption at the district governors’ office and municipalities, which could be due to lack of access to governors’ office and municipalities in such areas. However, opium poppy cultivation has strong correlation with insecurity and public perception of feeling unsafe.
-	Older district governors are associated with public optimism, better security situation and public perception of feeling safe. Older age is also associated with lower level of opium poppy cultivation. Age did not have a relationship with the experience of corruption at district governors’ office and municipalities.
-	More educated district governors are associated with competitive hiring process and better security. However, more education has a positive relationship with greater level of experience of corruption at district governors’ office and municipalities.
-	Native district governors are associated with insecurity and higher level of opium poppy cultivation. Nativity does not have any relationship with public perceptions at the national level.
-	Competitively hired district governors are associated with higher level of education, non-nativity and better security. However, there is no relationship between hiring process and public perceptions.
